version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - 8080:8080
      - 50051:50051
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_MODULES=text2vec-huggingface
      - DEFAULT_VECTORIZER_MODULE=text2vec-huggingface
      - HUGGINGFACE_INFERENCE_APIKEY=${HUGGINGFACE_API_KEY}
      - WEAVIATE_ENABLE_GRPC=true
    volumes:
      - ./data:/var/lib/weaviate
    networks:
      - weaviate-network

networks:
  weaviate-network:
    driver: bridge